name1 = csy
curName1 = $(name1)
name1 = caishanyu

name2 = csy
curName2 := $(name2)
name2 = caishanyu

name3 = csy
curName3 ?= $(name3)

curName4 ?= caishanyu

print:
	@echo curName1: $(curName1)
	@echo curName2: $(curName2)
	@echo curName3: $(curName3)
	@echo curName4: $(curName4)